### ISSUE TITLE
Nothing works!

### ISSUE THREAD

**Issue by ajxanman** [ajxanman/ScoutTests#1]
My two windows pop up and then it's just blank with a spinning wheel at the top! Please help!

**Comment by ajxanman** [comment]
@tswicegood

**Comment by tswicegood** [comment]
Occasionally a spinning wheel at the top is what you want. Can you outline the problem more, @ajxanman? What is the expected behavior? What have you done to get it to that point?

**Comment by ajxanman** [comment]
It is supposed to look kinda look like this: ajxanman.github.io/scoutingadvetures/ except in the place of the "Camp" button is a "Hike" button and when you click it runs the function Hike(). Class doesn't do anything yet. Thanks for helping, @tswicegood !
