### ISSUE TITLE
None of the functions work

### ISSUE THREAD

**Issue by ajxanman** [ajxanman/ScoutTests#2]
I fixed the crashing problem by removing the "for" loop on the rank switch, but now the three active buttons ("Click here to see rank!'',"Click here to see points!", and the"Hike" button) don't work! When you click on "Hike" it is supposed to run the hike() function, but it just sits there! Please help, @tswicegood !

**Comment by ajxanman** [comment]
I just looked at the console errors: When a function is called, I get the error "Uncaught RefrenceError: hike is not defined"! It does that with whatever function is called!

**Comment by ajxanman** [comment]
I changed the method of showing the points and now it is on line 49 and 50. It shows this error: "Uncaught TypeError: Cannot set property 'onclick' of null"! I don't know why it says 'null'.

**Comment by ajxanman** [comment]
I narrowed the problem down to the hike() function. Whatever script tag it's in, it cancels all code in that tag! Please take a look at it, @tswicegood

**Comment by ajxanman** [comment]
DONE! Solution: I re-wrote the code in the hike() function.

**Comment by tswicegood** [comment]
Did ya figure out what caused it?

**Comment by ajxanman** [comment]
Yes. It was the hike function. I don't know why, but it canceled all code in the script it was in.
